# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MlApp', '0003_remove_goods_dealerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppingbag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifics', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MlApp.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MlApp.User')),
            ],
        ),
    ]
