# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MlApp', '0005_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
